---
# vim: set ft=ansible:
- name: Install Consul Template
  unarchive:
    remote_src: yes
    src: "{{ item }}"
    dest: "/usr/local/bin"
  with_items:
    - "{{ _consul.download.consul_template_url }}"

- name: Create Consul Template Config Directory
  file:
    name: "{{ _consul.template.config_dir }}"
    state: directory
    owner: "root"
    group: "consul"
    mode: "0755"

- name: Create Consul Templates Directory
  file:
    name: "{{ _consul.template.config_dir }}/templates"
    state: directory
    owner: "root"
    group: "consul"
    mode: "0755"

- name: Create Consul Template systemd Script
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - "etc/systemd/system/consul-template.service"

- name: Disable Consul Template Service autostart
  service:
    name: "{{ item }}"
    enabled: no
  with_items:
     - "consul-template"
