# vim: set ft=ansible:

- name: Install Consul
  unarchive: remote_src=yes src="{{ item }}" dest="/usr/local/bin"
  with_items:
    - "{{ _consul.download.consul_url }}"
    - "{{ _consul.download.consul_template_url }}"

- name: Create consul group
  group: name="consul" state=present system=yes

- name: Create consul user
  user: name="consul" state=present system=yes group="consul" createhome=no home="/tmp" shell="/usr/sbin/nologin"

- name: Create Consul Config Directory
  file: name="{{ _consul.config_dir }}" state=directory owner="root" group="consul" mode="0755"

- name: Create Consul Defaults File
  template: src="etc/default/consul.j2" dest="/etc/default/{{ _consul.service_name }}" owner="root" group="root" mode="0755"

- name: Create Consul Upstart Script
  template: src="etc/init/consul.conf.j2" dest="/etc/init/{{ _consul.service_name }}.conf" owner="root" group="root" mode="0644"

- name: Create Consul Template Config Directory
  file: name="{{ _consul.template.config_dir }}" state=directory owner="root" group="consul" mode="0755"

- name: Create Consul Templates Directory
  file: name="{{ _consul.template.config_dir }}/templates" state=directory owner="root" group="consul" mode="0755"

- name: Create Consul Template Upstart Script
  template: src="etc/init/consul-template.conf.j2" dest="/etc/init/consul-template.conf" owner="root" group="root" mode="0644"

- name: Disable services autostart
  service: name="{{ item }}" enabled=no
  with_items:
     - "{{ _consul.service_name }}"
     - "consul-template"

