---
# vim: set ft=ansible:
- name: Create user and group for Consul
  include_tasks: consul_user_group.yml

- name: Install and configure Consul
  include_tasks: consul.yml

# Install Consul Template only when requested
- name: Install and configure Consul Temlate
  include_tasks: consul_template.yml
  when: _consul.template.install | default('false') | bool
