---
# vim: set ft=ansible:

- name: Install Consul
  unarchive:
    remote_src: yes
    src: "{{ item }}"
    dest: "/usr/local/bin"
  with_items:
    - "{{ _consul.download.consul_url }}"

- name: Create consul group
  group:
    name: "consul"
    state: present
    system: yes

- name: Create consul user
  user:
    name: "consul"
    state: present
    system: yes
    group: "consul"
    createhome: no
    home: "/tmp"
    shell: "/usr/sbin/nologin"

- name: Create Consul Config Directory
  file:
    name: "{{ _consul.config_dir }}"
    state: directory
    owner: "root"
    group: "consul"
    mode: "0755"

- name: Create Consul Defaults File
  template:
    src: "etc/default/consul.j2"
    dest: "/etc/default/{{ _consul.service_name }}"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create Consul systemd Script
  template:
    src: "etc/systemd/system/consul.service.j2"
    dest: "/etc/systemd/system/{{ _consul.service_name }}.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Create Consul Logrotate Configuration
  template:
    src: "etc/logrotate.d/consul.j2"
    dest: "/etc/logrotate.d/consul"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Disable services autostart
  service:
    name: "{{ item }}"
    enabled: no
  with_items:
     - "{{ _consul.service_name }}"

- name: Get package facts
  package_facts:
    manager: "auto"
  when: _consul.use_dnsmasq_forwarding|default(false)
  no_log: true

- name: Dnsmasq forwarding
  when: _consul.use_dnsmasq_forwarding|default(false) and 'dnsmasq' in ansible_facts.packages
  block:
    - name: Create dnsmasq config to forward consul domain to agent
      template:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
        mode: "0644"
      with_items:
        - "etc/dnsmasq.d/consul-forward.conf"
      register: dnsmasq_consul

    - name: Restart dnsmasq if config changed to enable consul queries
      service:
        name: dnsmasq
        state: restarted
      when: dnsmasq_consul is changed

# Install Consul Template only when requested
- name: Install and configure Consul Template
  include_tasks: consul_template.yml
  when: _consul.template.install | default('false') | bool
