# vim: set ft=ansible:

- name: Install Consul
  unarchive: remote_src=yes src="{{ item }}" dest="/usr/local/bin"
  with_items:
    - "{{ _consul.download.consul_url }}"
    - "{{ _consul.download.consul_template_url }}"

- name: Create Consul Config Directory
  file: name="{{ _consul.config_dir }}" state=directory owner="root" group="root" mode="0755"

- name: Create Consul Defaults File
  template: src="etc/default/consul.j2" dest="/etc/default/{{ _consul.service_name }}" owner="root" group="root" mode="0755"

- name: Create Consul Client Upstart Script
  template: src="etc/init/consul.conf.j2" dest="/etc/init/{{ _consul.service_name }}" owner="root" group="root" mode="0644"

- name: Disable service autostart
  service: name="{{ _consul.service_name }}" enabled=no

